language: python

python:
  - 3.5
  - 3.6
  - 3.7

before_install:
  - script/setup

script:
  - script/test

jobs:
  include:
    - stage: distribute
      if: branch = master AND type != pull_request
      install: skip
      script:
        - script/distribute
