#!/usr/bin/env bash
. script/env
set -xe
autopep8 --in-place --recursive --max-line-length 1000 --aggressive keras_model_specs tests
autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive keras_model_specs tests
