#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Run tests and lint checks.
PYTHONPATH="." pytest --cov=./ -s -v $ARGS
flake8 --max-line-length 50000 keras_model_specs tests

# Upload coverage for CI.
if [ -n "$CI" ]; then
  pip install codecov
  codecov
fi
